spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    enabled: ${RUN_DB_MIGRATIONS:false}

server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.data: INFO
    org.springframework.jdbc.core: INFO
    it.consolemania.catalog: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  server:
    port: 9001
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
