version: "3.9"

services:
  edge_service:
    image: ghcr.io/carlomicieli/edge-service:latest
    ports:
      - 8000:8000
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - CATALOG_SERVICE_URL=http://catalog_service:9000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  catalog_service:
    image: ghcr.io/carlomicieli/catalog-service:latest
    depends_on:
      catalog_db:
        condition: service_healthy
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - JAVA_TOOL_OPTIONS=-Xss512k -Xmx256M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M
      - DB_URL=jdbc:postgresql://catalog_db:5432/catalog
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - backend

  catalog_db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: catalog
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - catalog-db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ CMD-SHELL, 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4:6.18
    depends_on:
      catalog_db:
        condition: service_healthy
    ports:
      - 9080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./.docker/pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./.docker/pgadmin/pgpass:/pgpass # passwords for the connections in this file
    networks:
      - backend

networks:
  backend:

volumes:
  catalog-db-data:
