global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'edge-service'
    scrape_interval: 2s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'edge-service:8001' ]
  - job_name: 'catalog-service'
    scrape_interval: 2s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'catalog-service:9001' ]
