spring:
  application:
    name: games-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamesdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s
  liquibase:
    enabled: false

server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    com.example.consolemania.games: INFO

management:
  server:
    port: 9001
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
